    head = Node(11)
    head.next = Node(11)
    head.next.next = Node(11)
    head.next.next.next = Node(13)
    head.next.next.next.next = Node(13)
    head.next.next.next.next.next= Node(20)
    head.display()
    head.removeDuplicates()
    head.display()